### PR TITLE
Remove from translation

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Why? I thought, un other languages this might be translated in other words...?

**Comment by Valdnet** [comment]
These strings appear as follows:
```
@string/edit
@string/simple_save
```
How do you translate it 😁?

**Comment by stefan-niedermann** [comment]
Well, the idea was to use the values of `edit` and `save` in english, while there might be shorter or better translations in other languages - keeping the references if appropriate and for example use other values if there are better / shorter terms 😄 

But i'll remove the strings if you have another opinion 🤷‍♂️

**Comment by Valdnet** [comment]
A good idea, but for translators at Transifex it looks like this:

obraz
obraz

For a translator, a text string is a text string and must be translated. It is most convenient to change its value to the words present, if it does not have to be in this form 😉.

**Comment by stefan-niedermann** [comment]
Well, in this case i'll remove the extra strings completely and just use thw originals :) Seems to be more straight forward than duplicating them in the hope that there are shorter versions.

**Comment by Valdnet** [comment]
I think so too 😉. In this case, I am closing PR 😁.

**Pull request closed without merging**
