### PR TITLE
Correct app name

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Review by stefan-niedermann — CHANGES_REQUESTED** [review]
Good catch, but we should wrote `Deck web app` to make clear that not the android client is meant
(Respective `Deck Android app`)

**Comment by desperateCoder** [comment]
While we're already here... I think we should change "android" to "Android" (upper case)

**Comment by Valdnet** [comment]
@stefan-niedermann Or maybe it should be changed to: `Nextcloud Deck app`.

**Comment by stefan-niedermann** [comment]
I'm not sure whether this is enough for a user to distinguish the different platforms, since the Android app is also called "Nextcloud Deck" in the app stores...

So i had a closer look at how those strings are used. Let's go for

key | value | explanation
--- | --- | ---
`update_deck` | Update Deck web app | This is used as a title for a dialog which is followed by the next string
`deck_outdated_please_update` | Your Deck web app version is too old (%1$s). Please update to use this Android app as client.
`your_deck_version_is_too_old` | | I just noticed this seems to be not used anymore. grafik |


And as @desperateCoder mentioned, yes, would be nice if you could use this opportunity to write `Android` instead of `android` :slightly_smiling_face:

**Comment by desperateCoder** [comment]
Pepe ❤️ 

You won.

**Comment by Valdnet** [comment]
Corrected 😉.

**Review by stefan-niedermann — APPROVED** [review]

**Comment by stefan-niedermann** [comment]
Thank you! 🙂

**Pull request merged**
