### PR TITLE
Files -> Android

### PR DESCRIPTION
**Pull request by kesselb**
Not sure if that is better but I didn't know first what the Nextcloud Files app could be ;)

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Not sure. We put a link on it and many people didn't understand the difference between "Nextcloud Android" and "Nextcloud Deck Android" / "Nextcloud Notes Android"...

**Comment by kesselb** [comment]
I see. It's quite confusing.

Nextcloud
Nextcloud for Android

Nextcloud Deck
Nextcloud Deck for Android

Nextcloud Notes
Nextcloud Notes for Android

That could work. Most people don't associate apps with Nextcloud. You will figure something out ;)

**Comment by stefan-niedermann** [comment]
So in order to get "Nextcloud Deck for Android" work you will have to install "Nextcloud Deck" on your "Nextcloud" and "Nextcloud for Android" on your phone. 😳😁

Phew 😓 I really really wished, they went for "Plug-Ins" or "Add-Ons" instead of "Apps".

If we change the wording, we should change it everywhere. There are `.txt`-files in the `fastlane` folder which contain the wording, too.

And since the wording is identical to the wording in the Nextcloud Notes for Android app, could you do the PR there, too? I will take care about

- [ ] Google Play Store description
- [ ] Nextcloud App Store description

for both apps.

**Comment by kesselb** [comment]
> So in order to get "Nextcloud Deck for Android" work you will have to install "Nextcloud Deck" on your "Nextcloud" and "Nextcloud for Android" on your phone. flushedgrin

:see_no_evil:

**Pull request merged**
