### PR TITLE
WIP: Editing

### PR DESCRIPTION
**Pull request by stefan-niedermann**
device-2019-03-03-191745

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Hi @stefan-niedermann @desperateCoder how would we want to integrate this?
One idea I had in mind would be to make it work kind of like the actual Android contacts app (Android OS App) so that this would be like a master-detail flow where the card would be shown in "read-mode" with a FAB for editing and where the layout would be close to the details view on the webUI (viewpager for activity, attachments, etc.) I am just asking because at some pont in case attachements and the activity stream would be integrated then I'd say we could just put this into pager fragments.

Of course all this can be done at a far later point in time :)

**Comment by juliushaertl** [comment]
> One idea I had in mind would be to make it work kind of like the actual Android contacts app (Android OS App) so that this would be like a master-detail flow where the card would be shown in "read-mode" with a FAB for editing and where the layout would be close to the details view on the webUI (viewpager for activity, attachments, etc.) I am just asking because at some pont in case attachements and the activity stream would be integrated then I'd say we could just put this into pager fragments.

The contacts app is a bit different, since all contact details have a individual actio (like call a number). The only action we have is the editing one, so I think inline editing would be the best mode here. In general having the details in a view pager makes sense to me. (Note that we might merge the duedate/assigned users/... entries to the first tab in the web ui as well during the sidebar standardization for 16)

**Comment by AndyScherzinger** [comment]
> so I think inline editing would be the best mode here

sounds good to me

> having the details in a view pager makes sense to me

So all the actual tabs in the webUI will remain? What would be the content and name/icon of the then to be created tab you plan to do for Nc16?

**Comment by juliushaertl** [comment]
@AndyScherzinger The standardization issue is here https://github.com/nextcloud/server/issues/10289 It basically reduces the tabs to Details, Sharing, Activity I still need to do some thinking about how we handle that in deck, since sharing doesn't make a lot of sense on cards. But we will probably end up with
- Details (due date, assigned users, labels, description
- Activity (merged comments and activity stream)
- Attachments

**Comment by AndyScherzinger** [comment]
@juliushaertl @stefan-niedermann see latest screenshot, added tabs for the details screen :)

**Comment by juliushaertl** [comment]
Looks pretty nice already. :+1:

**Comment by stefan-niedermann** [comment]
Indeed :) We could put the modified and created date as a subheader into the action bar, i am not sure how important it is. Also personally i think the description might be more important than the other stuff (put it on top??)

**Comment by AndyScherzinger** [comment]
No real idea about the ordering to be honest. I'd say we should maybe try to keep it in the order the webUI uses (not sure about the actual order) while like with the tabs I think it would be nice to already implement it the way @juliushaertl plans to implement it in the upcoming versions.

Information designers to the rescue please :)

**Comment by AndyScherzinger** [comment]
The creation and modification dates could probably go into the toolbar, sure. They can't be explicitly changed anyways :)

**Comment by jancborchardt** [comment]
The title "Edit" should have a more relevant label. :) Like the card name. And for new cards, say "New card in `board name`" for example.

**Comment by AndyScherzinger** [comment]
@desperateCoder I can't run this branch anymore:
```
2019-02-20 10:35:58.412 4254-4309/it.niedermann.nextcloud.deck E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: it.niedermann.nextcloud.deck, PID: 4254
    java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
        at android.arch.persistence.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:135)
        at android.arch.persistence.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:115)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:151)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:409)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:96)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
        at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:233)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl.countAccounts(AccountDao_Impl.java:222)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.lambda$hasAccounts$1(DataBaseAdapter.java:47)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.-$$Lambda$DataBaseAdapter$8KCCinb2dlAPDc7JlSfzvyq9cFI.returnIntoLiveData(Unknown Source:2)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.lambda$wrapInLiveData$0(DataBaseAdapter.java:41)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.-$$Lambda$DataBaseAdapter$gxSG3hyGJt2kfoZZOpzaeBloyg0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by AndyScherzinger** [comment]
Nevermind, a complete wipe helped while I now don't see any boards anymore since for some reasons the SSO part fails :/

**Comment by desperateCoder** [comment]
:+1: I was about to suggest it. Have fun! :D

**Comment by AndyScherzinger** [comment]
@desperateCoder still have the issue with the SSO thingy... :/

**Comment by AndyScherzinger** [comment]
Now it works for some reason?!... Weird...

**Comment by desperateCoder** [comment]
Oh yeah, right. there sould be a SSO folder inside the project, just clone the add-annotaions branch of @David-Development s SSO Lib: https://github.com/nextcloud/Android-SingleSignOn.git (origin/add-annotations)

**Comment by AndyScherzinger** [comment]
@desperateCoder I actually use that branch via jitpack directly ;) But it still doesn't work in a stable way (don't see cards at the moment)

**Comment by desperateCoder** [comment]
Weird, works great for me... Maybe pull the current state? There were some changes since back then you were working on it

**Comment by AndyScherzinger** [comment]
@desperateCoder I run https://github.com/nextcloud/Android-SingleSignOn/tree/add-annotations (latest & greatest) ;) - Cards now get shown when not being on my wifi (seem to have some connectivity issues).

Btw, when I hit pull-to-refresh it alsways replaces the real cards with example cards ?!

**Comment by desperateCoder** [comment]
@AndyScherzinger Sounds like a "feature" from my friend @stefan-niedermann ... I actually have no clue what the UI does, all i am thinking about is providing some functionality to it. Maybe he implemented that for testing purposes, since the backend-part was completely destroyed by me for quite a while in favor to get Room to work. 

Do you need any more input to be able to work? Is the WiFi-problem a blocker? It works for me...

**Comment by AndyScherzinger** [comment]
> Do you need any more input to be able to work? Is the WiFi-problem a blocker? It works for me...

Nope, all good now 👍

**Comment by AndyScherzinger** [comment]
@desperateCoder see https://github.com/stefan-niedermann/nextcloud-deck/pull/25/commits/9d784ba5dcd413556ce0475b742d859ef0b059fd#diff-17569f034777f5e508564c36fef6a88bR94 for whatever reason, on the edit Activity's fragment(s) the labels are null (the list of labelIds is size=5 though). Any idea how to get the actual labels? :)

**Comment by desperateCoder** [comment]
What entity are we talking about? I'm currently at work, can't tell what exactly you are talking about. My current state of knowledge: due to limitations of the room framework I can deliver the IDs of the labels bundled with an associated entity, for any more details just request the entities for the iDs by using the sync manager. Did this help?

**Pull request merged**
