### PR TITLE
#455 ➕ Clone boards with existing stacks and labels

### PR DESCRIPTION
**Pull request by stefan-niedermann**
- [x] Offline clone throws errors
- [x] Fails because title is not unique
- [x] Adjust SyncAdapter when target account instance is on another host
- [x] `LiveData` does never complete because
     the `ResponseCallback` in `SyncManager#542` where a new `SyncHelper` is instantiated does never complete

### CODE REVIEW

**Comment by desperateCoder** [comment]
@stefan-niedermann try to break it. I guess you will, just tell me what is still wrong.

**Comment by desperateCoder** [comment]
Can't reproduce. ResponseCallback is called and livedata is fired. Maybe a hickup?

**Comment by desperateCoder** [comment]
Yo @stefan-niedermann, I think you mentioned, you don't get the error any more? Right?

**Comment by stefan-niedermann** [comment]
Check todos in description. according to you a clone to another account which is not on the same instance will fail just like the `move card` operation.

**Comment by desperateCoder** [comment]
Right, thanks for the hint! But the LiveData _does_ complete, right?

**Comment by stefan-niedermann** [comment]
Didn't test again yet. Will test when the cross-instance-stuff is fixed so far

**Comment by desperateCoder** [comment]
@stefan-niedermann uhm.... I don't know how to clone to an other account, and at this point I'm afraid to ask... 
but i think i found the issue regarding to the never-returning `IResponseCallback`, hopefully fixed now.

**Comment by stefan-niedermann** [comment]
That's not yet possible via UI. Since you told me that it will cause the exact same error as when moving cards, i thought you were able to fix it without UI blindly. Will add UI soon.

**Comment by desperateCoder** [comment]
again, thanks for the hint! done.

**Pull request merged**
