### PR TITLE
#561 Do not sync all users of instance but use sharees OCS API

### PR DESCRIPTION
**Pull request by stefan-niedermann**
- [x] Duplicate entries
  I originally thought i can easily find and filter duplicate entries by providing a unique `localId` to the adapter. Unfortunately the users which are searched by the API do not have a `localId`, which makes sense. However, sorry: In this case the filtering of duplicate entries has to be done via the user name and should be done in the `UserSearchLiveData` :-/ @desperateCoder .

### CODE REVIEW

**Comment by desperateCoder** [comment]
I filter them now. Try again

**Comment by stefan-niedermann** [comment]
Still seeing duplicates in some situations.

Logs:

```
search() (UserSearchLiveData.java:38) → ###DeckUserSearch: UI triggered! term: pete
search() (UserSearchLiveData.java:38) → ###DeckUserSearch: UI triggered! term: pet
search() (UserSearchLiveData.java:38) → ###DeckUserSearch: UI triggered! term: pe
search() (UserSearchLiveData.java:38) → ###DeckUserSearch: UI triggered! term: p
postCurrentFromDB() (UserSearchLiveData.java:97) → ###DeckUserSearch: posting for term p: [User{primaryKey='peter', uid='peter', displayname='Peter', localId=4, accountId=1, id=null, status=1, lastModified=null, lastModifiedLocal=null} it.niedermann.nextcloud.deck.model.User@a120f06c, User{primaryKey='peter', uid='peter', displayname='Peter', localId=5, accountId=1, id=null, status=1, lastModified=null, lastModifiedLocal=null} it.niedermann.nextcloud.deck.model.User@a120f06c, User{primaryKey='peter', uid='peter', displayname='Peter', localId=6, accountId=1, id=null, status=1, lastModified=null, lastModifiedLocal=null} it.niedermann.nextcloud.deck.model.User@a120f06c]
postCurrentFromDB() (UserSearchLiveData.java:97) → ###DeckUserSearch: posting for term p: [User{primaryKey='peter', uid='peter', displayname='Peter', localId=4, accountId=1, id=null, status=1, lastModified=null, lastModifiedLocal=null} it.niedermann.nextcloud.deck.model.User@a120f06c, User{primaryKey='peter', uid='peter', displayname='Peter', localId=5, accountId=1, id=null, status=1, lastModified=null, lastModifiedLocal=null} it.niedermann.nextcloud.deck.model.User@a120f06c, User{primaryKey='peter', uid='peter', displayname='Peter', localId=6, accountId=1, id=null, status=1, lastModified=null, lastModifiedLocal=null} it.niedermann.nextcloud.deck.model.User@a120f06c]

```

**Comment by desperateCoder** [comment]
In fact, not a duplicate. Have a look at the local id. Better question: how did you manage to get Peter twice into your database?! Maybe we need a unique constraint here. Thought we have one though.... But the search seems to work well.

**Comment by stefan-niedermann** [comment]
After clearing storage the problem is gone. Probably old shitty stuff in the database of my emulator.

**Pull request merged**
