### PR TITLE
Clone of Notes's PR #1017 for Nextcloud Deck

### PR DESCRIPTION
**Pull request by TacoTheDank**
Clone of [this](https://github.com/stefan-niedermann/nextcloud-notes/pull/1017).

### 1st commit
- Delete obsolete files

### 2nd commit
- Update gradle wrapper to 6.7.1 using git bash

### 3rd commit
- Update buildTools to 30.0.3
- Reorganize libraries and generally make gradles easier to read
- Remove unneeded stuff in module build.gradles
  - Bump module minSdk to app module's 19
  - Bump their Google Material versions from 1.2.0 -> 1.2.1
- Remove unused libraries
- Replace unused colorpickerpreference 2.0.0 with its transitively used colorpickerview version of 2.1.1

### 4th commit
- Update colorpickerview 2.1.1 -> 2.1.8 ([changelog](https://github.com/skydoves/ColorPickerView/releases)) (2.1.9 has a breaking change I'm unsure of how to fix)
- Downgrade Retrofit 2.7.1 -> 2.6.4 (see [this](https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-270-2019-12-09))

### 5th commit
- Use preferred functions for ViewPager2 things

### 6th commit
- Remove an unused class

### 7th commit
- Use some Compat classes

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Awesome, thanks! I'll have a look soon.

**Comment by desperateCoder** [comment]
@TacoTheDank oh wow, thanks man!

@stefan-niedermann regarding retrofit downgrade: we need to check if there are any incompatibilies regarding sso, I remember some obstacles here.

**Review by stefan-niedermann — APPROVED** [review]
Awesome contribution, thank you very much for doing the housekeeping for us :smile: !

Is it some kind of best practice to only have a `.gitignore` file in the root directory instead of each module? I though it makes sense that each module defines which files are for example build artifacts because each module also has it's own `build.gradle` file :man_shrugging: ?

PS.: When I saw this at your [GitHub profile](https://github.com/TacoTheDank)
grafik
I immediately was reminded of [this issue](https://github.com/stefan-niedermann/nextcloud-deck/issues/781) - if you want to have a look at it, and you are able to solve it: We have bounties for contributors :wink:

**Comment by desperateCoder** [comment]
Regarding Retrofit: 

https://github.com/nextcloud/Android-SingleSignOn/blob/bd009d249e09b1f0372aaeaa55a8a51185b46bcc/build.gradle#L142-L144

> because '2.7.0 requires okhttp:3.14.x which requires API level 19'

So we should go for 2.6.4, just as in this PR.

@TacoTheDank thanks again! :smiley:

**Comment by TacoTheDank** [comment]
> Is it some kind of best practice to only have a `.gitignore` file in the root directory instead of each module? I though it makes sense that each module defines which files are for example build artifacts because each module also has it's own `build.gradle` file 🤷‍♂️ ?

It's a personal best practice for me, because I like to think the fewer files required in a repo in general, the better. So if everything can be done in the root .gitignore, there is no need for module .gitignores :)

**Pull request merged**
