### PR TITLE
#453 🔀 Move cards to other boards and accounts

### PR DESCRIPTION
**Pull request by stefan-niedermann**
Sounds good, doesn't work.

```
2020-06-29 23:12:59.452 1159-2478/it.niedermann.nextcloud.deck.dev E/AndroidRuntime: FATAL EXCEPTION: Thread-37
    Process: it.niedermann.nextcloud.deck.dev, PID: 1159
    java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$deleteCard$24$SyncManager(SyncManager.java:914)
        at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$Si98zhSUvp3_LyrsS-TtPUbEbh8.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:919)
```

### CODE REVIEW

**Comment by desperateCoder** [comment]
the above error is fixed (for now), need more UI here. Currently we are just reordering (because always same board) - with extra steps (Drag n' Drop would be too easy i guess).

**Comment by stefan-niedermann** [comment]
UI for moving to other boards and accounts has been implemented. Moving to another board crashes:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$deleteCard$24$SyncManager(SyncManager.java:918)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$Si98zhSUvp3_LyrsS-TtPUbEbh8.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by desperateCoder** [comment]
There was a race condition. Fixed. Seems to work quite well on- and offline, as well as cross account. 

But I am really concerned, because the user might think that we preserve comments, attachments and stuff... But on the other hand: supporting this will open at least three gates of hell... I'm clueless, what would be the best here. Maybe some kind of warn-dialogue which is only shown once?

**Comment by stefan-niedermann** [comment]
Current stacktrace when moving a card with labels from Account A to Account B on another Nextcloud instance:

```
2020-07-06 14:21:15.418 28679-30763/it.niedermann.nextcloud.deck.dev E/DeckLog: onError() (IResponseCallback.java:24) -> com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 400
        at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequest(AidlNetworkRequest.java:202)
        at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:119)
        at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:98)
        at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
        at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
        at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException: {"status":400,"message":"title must be unique"}
    
        at com.nextcloud.android.sso.InputStreamBinder.processRequest(InputStreamBinder.java:366)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStream(InputStreamBinder.java:169)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequest(InputStreamBinder.java:146)
        at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:85)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-07-06 14:21:15.422 28679-30771/it.niedermann.nextcloud.deck.dev E/DeckLog: onError() (IResponseCallback.java:24) -> com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 400
        at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequest(AidlNetworkRequest.java:202)
        at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:119)
        at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:98)
        at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
        at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
        at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException: {"status":400,"message":"title must be unique"}
    
        at com.nextcloud.android.sso.InputStreamBinder.processRequest(InputStreamBinder.java:366)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStream(InputStreamBinder.java:169)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequest(InputStreamBinder.java:146)
        at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:85)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-07-06 14:21:15.439 28679-30773/it.niedermann.nextcloud.deck.dev E/AndroidRuntime: FATAL EXCEPTION: Thread-691
    Process: it.niedermann.nextcloud.deck.dev, PID: 28679
    android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
        at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:114)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.JoinCardWithLabelDao_Impl.insert(JoinCardWithLabelDao_Impl.java:153)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.JoinCardWithLabelDao_Impl.insert(JoinCardWithLabelDao_Impl.java:26)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.createJoinCardWithLabel(DataBaseAdapter.java:287)
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$assignLabelToCard$40$SyncManager(SyncManager.java:1331)
        at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$QeSEQ36pqwRy0naavQmFnOZsc8w.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by desperateCoder** [comment]
Should work as expected now, no problems at testing for me so far... please try to break it (again)!

**Pull request merged**
