### PR TITLE
#289 📎 sources - Introduce bottom sheet dialog

### PR DESCRIPTION
**Pull request by stefan-niedermann**
# Description

This PR allows one to not only select files from the phone to upload, but also pick contacts and take photos directly from within the app.

# Help test

You can download and install the [**`APK`**](https://github.com/stefan-niedermann/nextcloud-deck/suites/1433875310/artifacts/24211702) safely in parallel to the production version.

# Screenshots

| 1 | 2 |
| --- | --- |
| attachments-1 |  attachments-2 |

### CODE REVIEW

**Comment by splitt3r** [comment]
Awesome work @stefan-niedermann ! It works great. Only a minor idea: Maybe reuse the UI (tab) structure form the web? Currently the images are shown as full images but e. g. a contact is shown in a table structure. The Web UI shows everything in a table structure.

**Comment by q-wertz** [comment]
Tested and works :tada: Thanks for the new feature.

Smartphone: Nokia 7 plus with Android 10
Server: Deck v 1.1.2

**Comment by stefan-niedermann** [comment]
Fantastic, thank you very much for testing @splitt3r & @q-wertz !

> Only a minor idea: Maybe reuse the UI (tab) structure form the web? 

I think the Web UI should do it the other way around: If one can generate a preview, we should show the preview and only fall back to the generic table layout if we can't show anything.

Also Nextcloud usually always displays a preview (even for `.txt` files in the web files app), so i guess Deck is the one who steps out of the line :wink:

**Comment by splitt3r** [comment]
> 
> 
> Fantastic, thank you very much for testing @splitt3r & @q-wertz !
> 
> > Only a minor idea: Maybe reuse the UI (tab) structure form the web?
> 
> I think the Web UI should do it the other way around: If one can generate a preview, we should show the preview and only fall back to the generic table layout if we can't show anything.
> 
> Also Nextcloud usually always displays a preview (even for `.txt` files in the web files app), so i guess Deck is the one who steps out of the line 😉

Very good point. But than maybe create a common structure to display images and other files alike? Anyway i think this is more of a follow up issue.

**Pull request merged**
