### PR TITLE
pragmatic fix for cut seemingly cut off at the bottom (#55)

### PR DESCRIPTION
**Pull request by timkittel**
Hi,
I have a pragmatic fix for #55 . Unfortunately, simply adding a `paddingBottom` to the `RecyclerView` in `app/src/main/res/layout/fragment_stack.xml` gives a white margin. Am I doing something wrong here?

So instead, I propose a pragmatic fix, that shows the cards correctly, but there is a slight margin when scrolling.

Is that alright?

PS: I assume that `paddingBottom` in `RecyclerView` giving a white margin is due to there being another element which then in turn contains the cards. Do you know which one that could be?

### CODE REVIEW

**Comment by desperateCoder** [comment]
@stefan-niedermann I have no clue what you all are talking about :rofl:, please help @timkittel out :grin:

**Comment by timkittel** [comment]
Thanks for the comment, `android:clipToPadding="false"` works. Additionally using `android:scrollbarStyle="outsideOverlay"` seems to fix the issue with the scrollbar as well.

**Comment by timkittel** [comment]
The CI seems to have failed due to not being able to connect to some sources. Can you restart it?

**Comment by desperateCoder** [comment]
Done. Are you done? May I merge your PR?

**Comment by timkittel** [comment]
Yes, please.

**Comment by desperateCoder** [comment]
@timkittel thanks for your contribution!

**Comment by stefan-niedermann** [comment]
Great! Thank you very much for the contribution @timkittel :rocket:

Looking forward to further PRs :smiley:

**Pull request merged**
