### PR TITLE
Fix sso issues

### PR DESCRIPTION
**Pull request by David-Development**

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Great, with this patch i get a HTTP status code `412` (Precondition failed), i think it might be caused by not requesting a token (or does the lib this automatically?). I tried to use `AccountImporter.requestAuthToken(this, getIntent());`, but it didn't make a difference.

Here is the corresponding stack trace:

```
2018-10-11 18:02:19.259 8563-8583/it.niedermann.nextcloud.deck W/.nextcloud.dec: Accessing hidden method Landroid/app/ActivityThread;->currentApplication()Landroid/app/Application; (light greylist, reflection)
2018-10-11 18:02:19.263 8563-8583/it.niedermann.nextcloud.deck W/System.err: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 412
2018-10-11 18:02:19.266 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:237)
2018-10-11 18:02:19.266 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:191)
2018-10-11 18:02:19.266 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at com.nextcloud.android.sso.api.NextcloudAPI$3.subscribe(NextcloudAPI.java:178)
2018-10-11 18:02:19.270 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
2018-10-11 18:02:19.270 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10903)
2018-10-11 18:02:19.270 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10889)
2018-10-11 18:02:19.271 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10818)
2018-10-11 18:02:19.271 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at it.niedermann.nextcloud.deck.MainActivity$2$2.run(MainActivity.java:82)
2018-10-11 18:02:19.271 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-10-11 18:02:19.271 8563-8583/it.niedermann.nextcloud.deck W/System.err: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 412
2018-10-11 18:02:19.271 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:237)
2018-10-11 18:02:19.272 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:191)
2018-10-11 18:02:19.272 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at com.nextcloud.android.sso.api.NextcloudAPI$3.subscribe(NextcloudAPI.java:178)
2018-10-11 18:02:19.272 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
2018-10-11 18:02:19.272 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10903)
2018-10-11 18:02:19.272 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10889)
2018-10-11 18:02:19.272 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10818)
2018-10-11 18:02:19.272 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at it.niedermann.nextcloud.deck.MainActivity$2$2.run(MainActivity.java:82)
2018-10-11 18:02:19.272 8563-8583/it.niedermann.nextcloud.deck W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by David-Development** [comment]
> i think it might be caused by not requesting a token

the request will fail with a `TokenMismatchException` as seen here: https://github.com/nextcloud/android/blob/master/src/main/java/com/nextcloud/android/sso/InputStreamBinder.java#L155 and here: https://github.com/nextcloud/Android-SingleSignOn/blob/2b70d60b4371a6e0761459086b16d3a47b04f925/src/main/java/com/nextcloud/android/sso/exceptions/SSOException.java#L91


> I get a HTTP status code 412

Make sure that the API works as expected. Is there any way to test if the response is okay? (API endpoint is up and working properly). The http status code occurs on the Nextcloud Files App side. However no processing happens there. The raw http stream is passed on to your app. So a 412 usually means that something is wrong with the request..(I guess). Let me know if there is anything that I can test or validate.

Here is the code used for the Network request in the Nextcloud Files App:
https://github.com/nextcloud/android/blob/master/src/main/java/com/nextcloud/android/sso/InputStreamBinder.java#L172

https://github.com/nextcloud/android/blob/master/src/main/java/com/nextcloud/android/sso/InputStreamBinder.java#L214

**Comment by stefan-niedermann** [comment]
```
Make sure that the API works as expected. Is there any way to test if the response is okay? (API endpoint is up and working properly). The http status code occurs on the Nextcloud Files App side. However no processing happens there.
```

Yes i can confirm the API works as expected since the web interface uses exactly the same endpoint via XHR and works perfect.

We will check the other information you gave us and write here if we have updates for you :)

and: thank you for supporting us here!!

**Comment by desperateCoder** [comment]
You, sir, deserved a Cookie! Thanks for the  source-links and the fast Response!

I guess the API works well, since the web-app does also. Gonna be fun

**Comment by David-Development** [comment]
> Yes i can confirm the API works as expected since the web interface uses exactly the same endpoint via XHR and works perfect.

Okay, no idea then.. 😕 Is it the "normal" deck app from the app store? Maybe I can run some tests as well.

> thank you for supporting us here!!

For sure, looking forward to see more apps using it! Now we can make the sso library more stable and easier to use for developers! 


> finding the issue without the actual http-response-body

what do you mean exactly? The http body is (empty?) isn't it? As you can see here: https://github.com/nextcloud/android/blob/master/src/main/java/com/nextcloud/android/sso/InputStreamBinder.java#L214 we only parse the body if the status code is `200 <= http-status-code < 300` (basically any 200 status-code is fine).

**Comment by stefan-niedermann** [comment]
`Okay, no idea then.. confused Is it the "normal" deck app from the app store? Maybe I can run some tests as well.`

Yes, its the deck app: https://apps.nextcloud.com/apps/deck

Author is @juliushaertl

**Comment by David-Development** [comment]
@stefan-niedermann @desperateCoder 

Alright.. actually there is a body in the `412` response.. 

```json
{"message":"CSRF check failed"}
```

**Comment by David-Development** [comment]
> Gibt es eine Möglichkeit, bei der API statt einer Activity/Context nur den ApplicationContext 

Certainly! Check out the example at the news app: https://github.com/nextcloud/news-android/blob/master/News-Android-App/src/main/java/de/luhmer/owncloudnewsreader/NewsReaderApplication.java#L25

I would recommend creating the API once in the Application context as it survives the whole lifetime of the app and you don't have to recreate/re-init it every time you open another activity.

In gerneral it doesn't matter what kind of context you pass in there. It all just a question about the life-cycle of the API and possible memory leaks that go along with different solutions (application context / activity context / fragment context).
 

> wenn man sich nicht um Threads kümmern müsste, wie eben in deinem PR geschehen... Kann doch keiner ahnen

Well if the exception handling worked properly, it should've been easy to figure out what was going wrong. I kept it this way to allow the developer to decide what he needs. As he might execute some background sync and does not need the UI Thread (not exactly sure about the consequences right now - would have to think about it again)

**Comment by juliushaertl** [comment]
First, thank you all for getting this started. It is really awesome to see a community coming together to build an app for deck. :+1: 

> Alright.. actually there is a body in the 412 response..
> {"message":"CSRF check failed"}
> Not sure if that's an issue of the deck server app. The nextcloud news app works just fine.. not sure.

It seems you are actually using the old endpoints, that were built for the web app only. For the public REST API you will need to use the recent beta release, which you can find over here: https://github.com/nextcloud/deck/releases/tag/v0.5.0-beta1

Unfortunately I haven't had time to properly generate an API documentation :see_no_evil: , but I will try to come up with something proper and complete over the weekend. 

A list of all available routes of the REST API can also be found here:
https://github.com/nextcloud/deck/blob/master/appinfo/routes.php#L80-L115

A shameful attempt of starting to document it is here:
https://documenter.getpostman.com/view/4848351/RWMCtV4r

I hope those links contain some links to help you get started. I'll keep you updated on the proper documentation.

**Comment by juliushaertl** [comment]
Also if you have any urgent question, feel free to join #nextcloud-deck on freenode irc and ping me there. :wink:

**Comment by desperateCoder** [comment]
Please don't assume, i know what i am talking about! :D

I am pretty good at Java but i suck in Android Environment, so correct me whenever i am talking nonsense please!

If someting is impossible or doesn't make sense IT IS totally fine! All i try to do is  getting this whole thing idiot-proof :D

Best regards
Artur

**Comment by stefan-niedermann** [comment]
@juliushaertl aaaaaah thanks a lot!

i changed the endpoint to `/index.php/apps/deck/api/v1.0/boards` and get

```
2018-10-11 22:45:05.991 9162-9191/it.niedermann.nextcloud.deck W/.nextcloud.dec: Accessing hidden method Landroid/app/ActivityThread;->currentApplication()Landroid/app/Application; (light greylist, reflection)
2018-10-11 22:45:05.994 9162-9191/it.niedermann.nextcloud.deck W/System.err: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 302
2018-10-11 22:45:05.994 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:237)
2018-10-11 22:45:05.994 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:191)
2018-10-11 22:45:05.994 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at com.nextcloud.android.sso.api.NextcloudAPI$3.subscribe(NextcloudAPI.java:178)
2018-10-11 22:45:05.994 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
2018-10-11 22:45:05.995 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10903)
2018-10-11 22:45:05.995 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10889)
2018-10-11 22:45:05.995 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10818)
2018-10-11 22:45:05.995 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at it.niedermann.nextcloud.deck.MainActivity$2$2.run(MainActivity.java:83)
2018-10-11 22:45:05.995 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-10-11 22:45:05.997 9162-9191/it.niedermann.nextcloud.deck W/System.err: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 302
2018-10-11 22:45:05.997 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:237)
2018-10-11 22:45:05.997 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:191)
2018-10-11 22:45:05.997 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at com.nextcloud.android.sso.api.NextcloudAPI$3.subscribe(NextcloudAPI.java:178)
2018-10-11 22:45:05.997 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
2018-10-11 22:45:05.997 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10903)
2018-10-11 22:45:05.998 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10889)
2018-10-11 22:45:05.998 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10818)
2018-10-11 22:45:05.998 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at it.niedermann.nextcloud.deck.MainActivity$2$2.run(MainActivity.java:83)
2018-10-11 22:45:05.998 9162-9191/it.niedermann.nextcloud.deck W/System.err:     at java.lang.Thread.run(Thread.java:764)

```

so `302` is obviously better than `40x`....

**Comment by David-Development** [comment]
@stefan-niedermann try setting `setFollowRedirects(true)` when building the NextcloudRequest :)

**Comment by stefan-niedermann** [comment]
with `0.5.0-beta` i was able to successfully request an api endpoint :tada:

**Comment by stefan-niedermann** [comment]
Thanks for your help @David-Development and @juliushaertl

**Comment by David-Development** [comment]
Glad that it's working now! 👍Made some more changes to the SSO API so that the response body will be propagated to the client app. This will make debugging easier next time :)

**Comment by juliushaertl** [comment]
@David-Development The SSO is really impressive. Such a nice improvement to Nextcloud apps. Thanks for all the work you are doing there. :clap:

**Comment by David-Development** [comment]
@juliushaertl Thank you :) Glad that developers are starting to use that feature for their apps. Hopefully we'll be able to make the whole Nextcloud for Android ecosystem easier for users to setup and use!

**Pull request merged**
